// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgOLcx3M_xzF4iUcKdcjr6Xx4iR1skFtE',
    appId: '1:406675548148:web:8d4828ce08ce0c37ee7ba1',
    messagingSenderId: '406675548148',
    projectId: 'store-app-fdb92',
    authDomain: 'store-app-fdb92.firebaseapp.com',
    storageBucket: 'store-app-fdb92.appspot.com',
    measurementId: 'G-WDK329GSD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbLm2tTkaXQT2SguDTBlSiTgljZidm2oc',
    appId: '1:406675548148:android:609d290bce82455dee7ba1',
    messagingSenderId: '406675548148',
    projectId: 'store-app-fdb92',
    storageBucket: 'store-app-fdb92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKllqZfk6p9LCi6q7Zdgs6ZNiBqnv-WmY',
    appId: '1:406675548148:ios:11c7991051914110ee7ba1',
    messagingSenderId: '406675548148',
    projectId: 'store-app-fdb92',
    storageBucket: 'store-app-fdb92.appspot.com',
    iosBundleId: 'com.example.storeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKllqZfk6p9LCi6q7Zdgs6ZNiBqnv-WmY',
    appId: '1:406675548148:ios:11c7991051914110ee7ba1',
    messagingSenderId: '406675548148',
    projectId: 'store-app-fdb92',
    storageBucket: 'store-app-fdb92.appspot.com',
    iosBundleId: 'com.example.storeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgOLcx3M_xzF4iUcKdcjr6Xx4iR1skFtE',
    appId: '1:406675548148:web:5875f4bb37c47f77ee7ba1',
    messagingSenderId: '406675548148',
    projectId: 'store-app-fdb92',
    authDomain: 'store-app-fdb92.firebaseapp.com',
    storageBucket: 'store-app-fdb92.appspot.com',
    measurementId: 'G-69BP9CQZEN',
  );
}
